### ISSUE TITLE
Disable picture in picture (PIP) on Android TV

### ISSUE THREAD

**Issue by brentonv** [moneytoo/Player#206] opened 2021-11-13 06:30 UTC
I've tried all different display modes on [different devices](https://i.ibb.co/BnpKP6v/pip.png) and it seems PIP is displaying as an option on Android TV and there is no way to disable it. Is this normal or are the player options not displaying correctly?

The reason I ask is that the button is easily pressed in error and there is [no way](https://i.ibb.co/HVfZCnQ/atv-pip1.png) to [escape PIP](https://i.ibb.co/1fPjfYN/atv-pip2.png) on Android TV without [force closing](https://i.ibb.co/6JWdMR1/atv-pip3.png) the player

If this is how it is intended, can you please consider including an option to disable PIP🙏

Thanks

**Comment by moneytoo** [comment] 2021-11-13 07:41
The PiP functionality is a standard Android OS feature. Closing/dismissing may be altered by the device manufacturer. On my devices and the emulator, I can switch and dismiss the PiP from controls on the home screen. The PiP should just work the same as in other apps offering PiP functionality.

<img src="https://user-images.githubusercontent.com/1071643/141610299-fac297e0-5c2f-4505-b178-92dc1acf6163.png" height="240">

**Comment by brentonv** [comment] 2021-11-13 13:51
Thanks for the reply @moneytoo.  As you can [see here](https://i.ibb.co/VMyGcCZ/pip-no-controls1.png) I don't get any such controls on the home screen of the very common Android TV device NVIDIA Shield Pro 2019. The [only option](https://i.ibb.co/s3VyYPP/pip-no-controls2.png) is to [force close](https://i.ibb.co/8gJ6VMJ/pip-no-controls3.png) the app from the app settings menu

**Comment by moneytoo** [comment] 2021-11-13 20:05
Switching the the app should also dismiss PiP. It should really be no different than with other apps (you may try for example PiP in Youtube/[SmartTubeNext](https://github.com/yuliskov/SmartTubeNext)).

**Comment by brentonv** [comment] 2021-11-14 01:51
> Switching the the app should also dismiss PiP

I already showed the [app switcher](https://i.ibb.co/s3VyYPP/pip-no-controls2.png). There is nothing there..

**Comment by moneytoo** [comment] 2021-11-14 06:32
Stock Android TV doesn't include app/task switcher so normally would need to select it from home screen/launcher. What happens when you do that?

**Comment by brentonv** [comment] 2021-11-14 07:10
> Stock Android TV doesn't include app/task switcher

NVIDIA Shield Pro 2019 definitely includes an app switcher but Just Player does not show. There is [nothing there](https://i.ibb.co/s3VyYPP/pip-no-controls2.png)

> you may try for example PiP in Youtube/[SmartTubeNext](https://github.com/yuliskov/SmartTubeNext)

This is SmartTubeNext in the [app switcher](https://i.ibb.co/dpqBqD4/stn.png)

> select it from home screen/launcher. What happens when you do that?

Selecting the app from launcher/app settings will restore the player again but this is clumsy. A setting to turn off PIP would be a better option. Please consider adding this

**Comment by moneytoo** [comment] 2022-11-28 16:05
Unfortunately I'm unable to reproduce this issue and therefore to do anything with it.

**Closed by moneytoo** 2022-11-28 16:05 UTC
Labels: wontfix
