### ISSUE TITLE
Buffer 

### ISSUE THREAD

**Issue by Filaero** [moneytoo/Player#514] opened 2023-09-25 10:02 UTC
If possible, please add a buffer in megabytes, as is implemented in the Vimu player. This will make your player perfect. Do it in increments of 5-10-15-20-40-60-80-100 megabytes. So that the buffer is written to RAM.

**Comment by moneytoo** [comment] 2023-09-30 19:55
Duplicate of #154.

**Closed by moneytoo** 2023-09-30 19:55 UTC

**Comment by Filaero** [comment] 2023-09-30 20:13
So are you implementing it or have you closed it and won’t do it?
