### ISSUE TITLE
New feature [zoom in all part of videos]

### ISSUE THREAD

**Issue by Stu75e** [moneytoo/Player#528] opened 2023-10-29 08:00 UTC
Adding a new feature to the app in this program when zooming in movies, we don't always need to zoom in the middle of the movie, sometimes we need to see the corners or other parts of a movie bigger, so it is necessary to zoom in such a way that any point can be zoomed.  You can zoom in on the movie. There are few apps that have this feature

For example, I've seen this feature in Samsung's app player and I'll give an example 

https://github.com/moneytoo/Player/assets/133971463/d3fb91b4-a60f-4f45-a217-8a851e21f4ee

**Comment by moneytoo** [comment] 2023-11-06 21:20
Duplicate of #101

**Closed by moneytoo** 2023-11-06 21:20 UTC
