### ISSUE TITLE
won't play mp3

### ISSUE THREAD

**Issue by mufarm** [moneytoo/Player#609] opened 2024-09-05 21:14 UTC
Hi,
I installed your app because I needed an mp3 player, but Just Player would not play the mp3s I had. I downloaded the mp3s from libro.fm and then, copied them to the phone. Fyi, another app played them, but 2 other apps did not.

 - Model: moto g power (XT2165DL)
 - OS: Android 12
 - Version 0.168

**Comment by moneytoo** [comment] 2024-09-05 21:44
https://github.com/moneytoo/Player#are-there-any-media-formats-it-cannot-play

> Just Player focuses on playing videos so audio only playback isn't officialy supported

Duplicate of #55

**Closed by moneytoo** 2024-09-05 21:44 UTC
