### ISSUE TITLE
Locking the video in portrait mode should prevent landscape mode

### ISSUE THREAD

**Issue by Fmoment1** [moneytoo/Player#304] opened 2022-05-01 06:52 UTC
Sometimes I just want to see stuff in portrait mode while lying on my side. This doesn't seem to be currently possible as the orientation sensor still works **despite** the video being locked. 

Tapping and holding a video locks it, preventing us from accidentally changing the video progress, increasing/decreasing the volume and brightness, etc. Why doesn't it lock the video orientation too?

I would really appreciate it if this is looked into! Thanks for the great app regardless.

**Comment by moneytoo** [comment] 2022-05-09 19:51
Duplicate of #227

**Closed by moneytoo** 2022-05-09 19:51 UTC
Labels: duplicate
