### ISSUE TITLE
Please make it possible to use opensubtitles, if you do that automatically just player will be the best video player in the world!

### ISSUE THREAD

**Issue by Root-FTW** [moneytoo/Player#330] opened 2022-07-15 06:50 UTC
If you need a donation to work on this function, please send me a message about how much you need, since your player is the best I've used in years, and it only needs to have the opensubtitles option to be 100% perfect

**Comment by moneytoo** [comment] 2022-07-19 20:39
Duplicate of #323

**Closed by moneytoo** 2022-07-19 20:39 UTC
