### ISSUE TITLE
Disable Subs Permanently?

### ISSUE THREAD

**Issue by EXOSKELTON89** [moneytoo/Player#274] opened 2022-02-16 21:30 UTC
Anyway to permanently have the subs turned off when playing a video? Just so we don't have to keep turning them off on every video we play :)

Thanks

**Comment by EXOSKELTON89** [comment] 2022-02-19 09:01
😬

**Comment by luniz7** [comment] 2022-02-21 03:13
Came here to ask the same thing.

**Comment by EXOSKELTON89** [comment] 2022-02-24 07:15
Haha I don't even know if these messages get read to be honest 😂

**Comment by luniz7** [comment] 2022-02-24 13:50
> Haha I don't even know if these messages get read to be honest 😂

Maybe, maybe not. You never know.

**Comment by moneytoo** [comment] 2022-12-10 21:38
Duplicate of #390

This option is now in the latest release

**Closed by moneytoo** 2022-12-10 21:38 UTC
