### ISSUE TITLE
Black screen with audio - Remux movies

### ISSUE THREAD

**Issue by najkmajt** [moneytoo/Player#378] opened 2022-10-25 08:16 UTC
Hi moneytoo. I am using Just player as my number one video player, but I have problems playing "remux 4k movies". Every time I try to play it, my screen goes black, but it plays sound. I tested other video players, such as default exo player, vlc, mxplayer etc. and I don't have that problem. Is there any way to fix this? I really like your player, so if you have any idea how to solve this issue I would be thankful. Enjoy your day !

**Comment by wfy2165968** [comment] 2022-10-25 15:43
I have the same problem

**Comment by moneytoo** [comment] 2022-10-25 15:54
Just Player uses ExoPlayer so it should generally play everything ExoPlayer plays. If you have issue with particular video file, please share a sample of such file.

**Comment by wfy2165968** [comment] 2022-10-25 22:56
The.Northman.2022.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
Everything.Everywhere.All.at.Once.2022.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
Minions.The.Rise.of.Gru.2022.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT

**Comment by moneytoo** [comment] 2022-10-26 19:47
> Minions.The.Rise.of.Gru.2022.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
```
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
```
This is a Dolby Vision file so with the latest stable ExoPlayer it plays only on devices supporting DV as it doesn't fallback to HDR. #166, https://github.com/google/ExoPlayer/issues/9794

**Comment by moneytoo** [comment] 2022-11-23 20:43
Release [v0.125](https://github.com/moneytoo/Player/releases/tag/v0.125) includes ExoPlayer [r2.18.2](https://github.com/google/ExoPlayer/releases/tag/r2.18.2) which has some DV related improvements. Does it work any better for you?

**Comment by moneytoo** [comment] 2022-11-29 23:02
Duplicate of #270. The one file I downloaded was DV profile 7. One of the upcomings update should include an option to fallback to HDR.

**Closed by moneytoo** 2022-11-29 23:02 UTC
