### ISSUE TITLE
Finer seek on short videos

### ISSUE THREAD

**Issue by UnlimitedCookies** [moneytoo/Player#367] opened 2022-09-16 04:36 UTC
I noticed that with videos that are like 6 seconds long you are only able to jump in full seconds. Here it would be cool to be able to seek with a finer sub-second deviation to find a certain frame for example.

**Comment by moneytoo** [comment] 2022-11-28 21:38
Duplicate of #172. I'm afraid that such feature is out of scope for this simple app.

**Closed by moneytoo** 2022-11-28 21:38 UTC

**Comment by UnlimitedCookies** [comment] 2022-11-29 20:18
Hmm, okay. But what would add the major complexity? Does the ExoPlayer not support this scenario, because in my mind, you just need to add steps to the seeking bar if the video is short enough (maybe in steps).

**Comment by moneytoo** [comment] 2022-11-29 20:43
Right now the seekbar seeks to [sync points](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SeekParameters.html) (which is faster than exact seeking) and it really depends on the video, how many sync points there are (based on key frames etc.). Sure, it could be modified so for videos under (let's say) 30 seconds the seek would be exact. But then I'm not sure if the playback would always start properly (without seeking to sync point) with all the formats. This makes it really marginal case for me (as I see the player intended mainly for movies and TV shows).
