### ISSUE TITLE
No subtitles when there are

### ISSUE THREAD

**Issue by sherpajosh** [moneytoo/Player#541] opened 2023-12-03 00:38 UTC
For some mkv files, Just Player doesn't see any subtitles that are part of the file. VLC recognizes and shows the subtitles without any problem. I am using the latest version on my Nvidia Shield. 

Below is all the available file information:

General

Format                         : Matroska
Format version                 : Version 4
File size                      : 5.46 GiB
Duration                       : 2 h 6 min
Overall bit rate               : 6 172 kb/s
Frame rate                     : 23.976 FPS
Writing application            : mkvmerge v65.0.0 ('Too Much') 64-bit
Writing library                : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L4@Main
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 2 h 6 min
Bit rate                       : 5 592 kb/s
Width                          : 1 920 pixels
Height                         : 804 pixels
Display aspect ratio           : 2.40:1
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Bits/(Pixel*Frame)             : 0.151
Stream size                    : 4.94 GiB (91%)
Writing library                : x265M - 3.4+35-772bb4c84:[Windows][GCC 10.2.0][64 bit] 10bit
Encoding settings              : cpuid=1111039 / frame-threads=2 / numa-pools=4 / wpp / no-pmode / no-pme / no-psnr / no-ssim / log-level=2 / input-csp=1 / input-res=1920x804 / interlace=0 / total-frames=182021 / level-idc=0 / high-tier=1 / uhd-bd=0 / ref=4 / no-allow-non-conformance / no-repeat-headers / annexb / no-aud / no-hrd / info / hash=0 / no-temporal-layers / open-gop / min-keyint=23 / keyint=250 / gop-lookahead=0 / bframes=8 / b-adapt=2 / b-pyramid / bframe-bias=0 / rc-lookahead=25 / lookahead-slices=4 / scenecut=40 / hist-scenecut=0 / radl=0 / no-splice / no-intra-refresh / ctu=64 / min-cu-size=8 / rect / no-amp / max-tu-size=32 / tu-inter-depth=1 / tu-intra-depth=1 / limit-tu=0 / rdoq-level=2 / dynamic-rd=0.00 / no-ssim-rd / signhide / no-tskip / nr-intra=0 / nr-inter=0 / no-constrained-intra / strong-intra-smoothing / max-merge=3 / limit-refs=3 / limit-modes / me=3 / subme=3 / merange=57 / temporal-mvp / no-frame-dup / no-hme / weightp / no-weightb / no-analyze-src-pics / deblock=-3:-3 / no-sao / no-sao-non-deblock / rd=4 / selective-sao=0 / no-early-skip / rskip / no-fast-intra / no-tskip-fast / no-cu-lossless / no-b-intra / no-splitrd-skip / rdpenalty=0 / psy-rd=2.00 / psy-rdoq=1.00 / no-rd-refine / no-lossless / cbqpoffs=0 / crqpoffs=0 / rc=crf / crf=18.0 / qcomp=0.60 / qpstep=4 / stats-write=0 / stats-read=0 / ipratio=1.40 / pbratio=1.30 / aq-mode=3 / aq-strength=1.00 / cutree / zone-count=0 / no-strict-cbr / qg-size=32 / no-rc-grain / qpmax=69 / qpmin=0 / no-const-vbv / sar=0 / overscan=0 / videoformat=5 / range=0 / colorprim=2 / transfer=2 / colormatrix=2 / chromaloc=0 / display-window=0 / cll=0,0 / min-luma=0 / max-luma=1023 / log2-max-poc-lsb=8 / vui-timing-info / vui-hrd-info / slices=1 / no-opt-qp-pps / no-opt-ref-list-length-pps / no-multi-pass-opt-rps / scenecut-bias=0.05 / hist-threshold=0.03 / no-opt-cu-delta-qp / aq-motion / no-hdr10 / no-hdr10-opt / no-dhdr10-opt / no-idr-recovery-sei / analysis-reuse-level=0 / analysis-save-reuse-level=0 / analysis-load-reuse-level=0 / scale-factor=0 / refine-intra=0 / refine-inter=0 / refine-mv=1 / refine-ctu-distortion=0 / no-limit-sao / ctu-info=0 / no-lowpass-dct / refine-analysis-type=0 / copy-pic=1 / max-ausize-factor=1.0 / no-dynamic-refine / no-single-sei / no-hevc-aq / no-svt / no-field / qp-adaptation-range=1.00 / scenecut-aware-qp=0conformance-window-offsets / right=0 / bottom=0 / decoder-max-rate=0 / no-vbv-live-multi-pass
Default                        : Yes
Forced                         : No

Audio #1
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : A_AAC-2
Duration                       : 2 h 6 min
Bit rate                       : 412 kb/s
Channel(s)                     : 6 channels
Channel layout                 : C L R Ls Rs LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 20 ms
Stream size                    : 373 MiB (7%)
Language                       : English
Default                        : Yes
Forced                         : No

Audio #2
ID                             : 3
Format                         : AAC LC SBR
Format/Info                    : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name                : HE-AAC
Format settings                : Explicit
Codec ID                       : A_AAC-2
Duration                       : 2 h 6 min
Bit rate                       : 66.2 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 23.438 FPS (2048 SPF)
Compression mode               : Lossy
Delay relative to video        : 40 ms
Stream size                    : 59.6 MiB (1%)
Title                          : Commentary
Language                       : English
Default                        : No
Forced                         : No

Text #1
ID                             : 4
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 2 min
Bit rate                       : 11.8 kb/s
Frame rate                     : 0.254 FPS
Count of elements              : 1867
Stream size                    : 10.4 MiB (0%)
Language                       : English
Default                        : No
Forced                         : No

Text #2
ID                             : 5
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 1 h 54 min
Bit rate                       : 387 b/s
Frame rate                     : 0.011 FPS
Count of elements              : 77
Stream size                    : 324 KiB (0%)
Title                          : Forced
Language                       : English
Default                        : No
Forced                         : Yes

Text #3
ID                             : 6
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 6 min
Bit rate                       : 21.5 kb/s
Frame rate                     : 0.330 FPS
Count of elements              : 2500
Stream size                    : 19.4 MiB (0%)
Title                          : Commentary
Language                       : English
Default                        : No
Forced                         : No

Text #4
ID                             : 7
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 5 min
Bit rate                       : 7 512 b/s
Frame rate                     : 0.212 FPS
Count of elements              : 1593
Stream size                    : 6.72 MiB (0%)
Language                       : Chinese
Default                        : No
Forced                         : No

Text #5
ID                             : 8
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 6 min
Bit rate                       : 13.9 kb/s
Frame rate                     : 0.308 FPS
Count of elements              : 2339
Stream size                    : 12.6 MiB (0%)
Title                          : Commentary
Language                       : Chinese
Default                        : No
Forced                         : No

Text #6
ID                             : 9
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 5 min
Bit rate                       : 7 915 b/s
Frame rate                     : 0.199 FPS
Count of elements              : 1495
Stream size                    : 7.08 MiB (0%)
Language                       : French
Default                        : No
Forced                         : No

Text #7
ID                             : 10
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 4 min
Bit rate                       : 7 182 b/s
Frame rate                     : 0.212 FPS
Count of elements              : 1591
Stream size                    : 6.42 MiB (0%)
Language                       : Korean
Default                        : No
Forced                         : No

Text #8
ID                             : 11
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 6 min
Bit rate                       : 13.4 kb/s
Frame rate                     : 0.309 FPS
Count of elements              : 2343
Stream size                    : 12.1 MiB (0%)
Title                          : Commentary
Language                       : Korean
Default                        : No
Forced                         : No

Text #9
ID                             : 12
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 5 min
Bit rate                       : 9 554 b/s
Frame rate                     : 0.214 FPS
Count of elements              : 1605
Stream size                    : 8.54 MiB (0%)
Language                       : Portuguese
Default                        : No
Forced                         : No

Text #10
ID                             : 13
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 6 min
Bit rate                       : 15.6 kb/s
Frame rate                     : 0.298 FPS
Count of elements              : 2259
Stream size                    : 14.1 MiB (0%)
Title                          : Commentary
Language                       : Portuguese
Default                        : No
Forced                         : No

Text #11
ID                             : 14
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 5 min
Bit rate                       : 8 529 b/s
Frame rate                     : 0.214 FPS
Count of elements              : 1608
Stream size                    : 7.63 MiB (0%)
Language                       : Spanish
Default                        : No
Forced                         : No

Text #12
ID                             : 15
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 6 min
Bit rate                       : 15.7 kb/s
Frame rate                     : 0.287 FPS
Count of elements              : 2176
Stream size                    : 14.2 MiB (0%)
Title                          : Commentary
Language                       : Spanish
Default                        : No
Forced                         : No

Text #13
ID                             : 16
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 5 min
Bit rate                       : 7 221 b/s
Frame rate                     : 0.219 FPS
Count of elements              : 1642
Stream size                    : 6.46 MiB (0%)
Language                       : Thai
Default                        : No
Forced                         : No

Text #14
ID                             : 17
Format                         : VobSub
Muxing mode                    : zlib
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 6 min
Bit rate                       : 15.9 kb/s
Frame rate                     : 0.309 FPS
Count of elements              : 2343
Stream size                    : 14.4 MiB (0%)
Title                          : Commentary
Language                       : Thai
Default                        : No
Forced                         : No

**Comment by moneytoo** [comment] 2023-12-27 11:20
Duplicate of #160

**Closed** 2023-12-27 11:21 UTC
