### ISSUE TITLE
Nice able to play Anime movies or videos

### ISSUE THREAD

**Issue by Rocky2242** [moneytoo/Player#95] opened 2021-04-28 03:12 UTC
![Screenshot_2021-04-28-08-43-48-29_5a080c45e0906ad77ba9417753301907](https://user-images.githubusercontent.com/57870860/116341082-ebd37380-a7fd-11eb-9a97-aa85c341c3ae.jpg)

**Comment by moneytoo** [comment] 2021-04-28 05:37
Isn't that video with 10 bit depth? Unfortunately, Android/ExoPlayer do not support that in AVC: #87. Share a sample or output of `mediainfo` for confirmation.

**Comment by Rocky2242** [comment] 2021-04-28 06:13
yuup its of 10 bit depth

**Comment by moneytoo** [comment] 2021-04-28 17:29
Duplicate of #87

**Closed by moneytoo** 2021-04-28 17:29 UTC
