### ISSUE TITLE
mkv sample does not play on PUS7304

### ISSUE THREAD

**Issue by pitrako** [moneytoo/Player#231] opened 2021-12-21 11:35 UTC
This sample doesn't play, but on nova and vimu it plays:
https://www.makemkv.com/download/dvtest/P4_LG_Dolby_Trailer_4K_Demo.mkv

**Comment by moneytoo** [comment] 2021-12-26 13:52
Looks like a duplicate of #184, so [the same applies here](https://github.com/moneytoo/Player/issues/184#issuecomment-965758154).

**Closed** 2021-12-26 17:19 UTC
