### ISSUE TITLE
Remember speed settings across the app

### ISSUE THREAD

**Issue by PetbkA** [moneytoo/Player#453] opened 2023-03-23 13:38 UTC
**Describe the bug**
This is a feature request.

Right now speed settings are being saved only for session. I.e. even if you'll reopen some video where speed level has been changed, level will return to _Normal_.

**To Reproduce**
1. Open _Video1_;
2. Change speed to e.g. _2x_;
3. Open _Video2_ - NOK, speed level will be _Normal_ again;
4. Open _Video1_ again - NOK, speed level is _Normal_ too, despite that it has been changed in step 2.

**Expected behavior**
Save speed level on "per app" basis (one value for all videos).

"Per app" basis is better 'cause of it's simplicity and the fact that usually speed level is constant across most of the videos (e.g. _NewPipe_ does it in such way).

**Device (please complete the following information):**
 - Model: Xiaomi Redmi Note 9 Pro 6/64 Gb
 - OS: crDroid 7.23 (Android 11)
 - Version: 0.137

**Comment by moneytoo** [comment] 2023-03-28 14:14
Duplicate of #233

**Closed by moneytoo** 2023-03-28 14:14 UTC
