### ISSUE TITLE
opening sound files

### ISSUE THREAD

**Issue by ocaeon** [moneytoo/Player#107] opened 2021-05-31 23:31 UTC
hi!  this player is so simple and effective i like to use it for audio too.  there are no other simple audio players, all have duplicated effort and service integration, they remind me of when the win xp 'media player' was suddenly completely bloated.. 

 so this app is wonderful, except this doesn't open audio files, i have to lie and say they are video files!   do i understand right that this is just because the file extensions are not listed in the manifest?  or is there deeper issue?  if adding ability to open sounds from file managers and galleries would add any battery drain, then nevermind. 

 ps, the in app file chooser shows the files but will not open them directly either, but i feel an in app chooser is not needed anyway!

**Comment by moneytoo** [comment] 2021-06-01 06:00
Duplicate of #55. Some feedback is already tracked there.

**Closed by moneytoo** 2021-06-01 06:00 UTC
