### ISSUE TITLE
Playlist m3u

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [moneytoo/Player#591] opened 2024-06-03 14:39 UTC
It would be great if the app could also open and run m3u Playlists

#### m3u list
https://github.com/iptv-org/iptv

In order to play Playlist m3u, you need to install other player VLC kodi.
Their players also have problems with format decoding, consume more resources on the phone and have a complicated interface.

**Comment by moneytoo** [comment] 2024-06-28 21:25
Duplicate of #167

**Closed by moneytoo** 2024-06-28 21:25 UTC
