### ISSUE TITLE
Delayed start up when root folder of videos is set. 

### ISSUE THREAD

**Issue by VasilisKos** [moneytoo/Player#534] opened 2023-11-12 14:12 UTC
When the root movies folder is set (the first time the app is launched, thus access to that folder appears to have been granted in Android settings), opening a video file through a file explorer (I use Solid Explorer) takes a few seconds (up to 10 some times) for the video to start playing. 
If no folder is set, or you delete access to the folder in Android settings, videos start immediately, with no delay at all. 

Device
 - Nokia 6.2
 - Android 11
 - Version 0.153 (maybe in earlier too)

**Comment by moneytoo** [comment] 2023-11-17 06:58
Duplicate of #429

**Closed by moneytoo** 2023-11-17 06:58 UTC
