### ISSUE TITLE
Add recycler view and show all videos of local file and click file to play

### ISSUE THREAD

**Issue by Munnapatel003** [moneytoo/Player#62] opened 2021-02-26 01:59 UTC
This is too good but media picker functionality is so irritating because why person try to play many videos and my time to use picker. My suggestion please Add recycler view and show all videos of local file and click  each file to play video

**Comment by moneytoo** [comment] 2021-02-26 07:42
Duplicate of #13

**Closed** 2021-02-26 07:42 UTC

**Comment by Munnapatel003** [comment] 2021-02-27 10:11
Thank you for your reply...
can you please suggest to me please? how to pass the media path from
adapter
like
  holder.itemView.setOnClickListener(new View.OnClickListener() {
       @Override
       public void onClick(View v) {
           Intent intent = new Intent(mContext, VideoFolderActivity.class);
           intent.putExtra(" FilePath ", FilePath.get(position) );
           mContext.startActivity(intent);
       }
        });


and how to add this in your code and where... suggest to me plese. I am
waiting for your reply. if you say. I will send you the whole project file.

**Comment by Munnapatel003** [comment] 2021-02-27 10:16
i want to pass this.


int position = -1;
position = getIntent().getIntExtra(" FilePath   ", -1);
  String path = getIntent().getStringExtra(" position ");

i want to only String path value which is Full  media File path
