### ISSUE TITLE
[feature request] Add option to customize touch gestures

### ISSUE THREAD

**Issue by jerryn70** [moneytoo/Player#156] opened 2021-08-19 05:46 UTC
Add an option to customize touch gesture according to user need and add more options like double tap to play/pause etc is a great help .
Se screenshot below 
![](https://i.imgur.com/JnjxJLA.jpg)

**Comment by moneytoo** [comment] 2021-08-19 05:49
> add more options like double tap to play/pause

Double tapping the center third already generates play/pause.

**Comment by jerryn70** [comment] 2021-08-19 11:22
@moneytoo oh sorry I forgot that . But ability customize is a good one I think

**Comment by moneytoo** [comment] 2021-08-19 14:19
Duplicate of #47

**Closed by moneytoo** 2021-08-19 14:19 UTC
