### ISSUE TITLE
Adjust audio sync

### ISSUE THREAD

**Issue by Noitarud** [moneytoo/Player#485] opened 2023-06-05 15:07 UTC
Does Exo permit advancing or delaying audio track against video track? Care to add an interface for it?
My other video player supports delaying by ms so I write what is required on the video filename, which may need to be set again if there is a corrupt spot in it.

For those interested in fixing theirs use mp4box. After extracting tracks, specify "-add filename#audio:delay=ms" for the audio (ms eg. "3000")

**Comment by moneytoo** [comment] 2023-08-16 21:57
Duplicate of #6

**Closed by moneytoo** 2023-08-16 21:57 UTC
