### ISSUE TITLE
suggestion for the player

### ISSUE THREAD

**Issue by Jeze001** [moneytoo/Player#236] opened 2021-12-28 14:32 UTC
Hello, I would like to make a suggestion for this excellent player, in which case it would be interesting if it could play the video with the cell phone screen off, often on the street we want to listen to an audio of a video with the cell phone in the pocket and the screen turned off , so it would be very good to play the video with the cell phone screen off.
Thank you very much in advance.

**Comment by moneytoo** [comment] 2021-12-28 19:48
Duplicate of #44

**Closed by moneytoo** 2021-12-28 19:48 UTC
