### ISSUE TITLE
Permanently disable Dolby Vision and fallback to HDR.

### ISSUE THREAD

**Issue by vegedb** [moneytoo/Player#392] opened 2022-11-21 08:38 UTC
Since there's barely any Dolby Vision android/androidtv devices, I suggest to disable it in the app rather than waiting for exoplayer to fix it.

According to this, https://github.com/google/ExoPlayer/issues/9794,
`if (format.sampleMimeType.equals(MimeTypes.VIDEO_DOLBY_VISION) 
        && want_to_disable_dv)`

DV can be disabled by editing a few lines and rebuilt.

Hope you can make another beta version of your app with the edited exoplayer for the time being for us. Don't think exoplayer will have an update anytime soon as its been more than a year since the issue.

**Comment by moneytoo** [comment] 2022-11-23 20:42
Release [v0.125](https://github.com/moneytoo/Player/releases/tag/v0.125) includes ExoPlayer [r2.18.2](https://github.com/google/ExoPlayer/releases/tag/r2.18.2) which has some DV related improvements so you might want to check that out.

**Comment by vegedb** [comment] 2022-11-24 03:10
> Release [v0.125](https://github.com/moneytoo/Player/releases/tag/v0.125) includes ExoPlayer [r2.18.2](https://github.com/google/ExoPlayer/releases/tag/r2.18.2) which has some DV related improvements so you might want to check that out.

That's a negative. Tested multiple DV videos, it still has black screen problems.

Any chance you could permanently disable it. DV is not supported in most android devices so it makes most sense I feel.

I've tried all video players, mxplayer, vlc, mpv, kodi, you name it. Just Player is the smoothest there is out there, its soooo close to be the perfect holy grain android player. Hope you would consider disabling the bane of DV for us.

**Comment by moneytoo** [comment] 2022-11-29 22:55
Duplicate of #270. Is this about DV profile 7 or some other profile?

**Closed by moneytoo** 2022-11-29 22:55 UTC
Labels: enhancement
