### ISSUE TITLE
Fade play GUI if playback is stopped.

### ISSUE THREAD

**Issue by Etim-Orb** [moneytoo/Player#322] opened 2022-06-29 15:02 UTC
When we pause a video the play GUI (such as the scrollbar and the icons) stay on the screen. Sometimes I stop video to check a detail and often the big white play button covers the content I want to see. I think it would be better for this interface to disappear after a few seconds just like when playing.

**Comment by Etim-Orb** [comment] 2022-06-29 20:23
Perhaps not even fade automatically but fade when tapped. This may also be an option.

**Comment by moneytoo** [comment] 2022-07-02 08:48
Duplicate of #195

**Closed by moneytoo** 2022-07-02 08:48 UTC
