### ISSUE TITLE
Make Media Controls Fade Away When Video Is Paused

### ISSUE THREAD

**Issue by MercerBoi** [moneytoo/Player#183] opened 2021-09-19 06:01 UTC
I'm not sure if I'm using the correct terminology, but when a video is playing, if you touch the screen once you get all the options such as pause/play, subtitles, video orientation, etc. If you touch the screen again, or just wait a few seconds, these options fade away. 

However, this is not the case when the video is paused, these options remain on the screen. This can be little inconvenient if you're trying to pause and take a screenshot. Making this change would be really appreciated.

(To add more, this would work by tapping on the screen on any area other than the pause/play button. Doing so would make the options fade away.)

**Comment by moneytoo** [comment] 2021-09-19 06:15
Duplicate of #89

**Closed by moneytoo** 2021-09-19 06:15 UTC
