### ISSUE TITLE
Add option to open url from Just player.

### ISSUE THREAD

**Issue by rozari0** [moneytoo/Player#400] opened 2022-12-05 11:24 UTC
If I want to stream I have to open URL from another app every time. It's kinda annoying.
Opening URL from the app itself would be very helpful.

**Comment by moneytoo** [comment] 2022-12-06 21:30
Duplicate of #106.

But how do you find that url? Do you type it entirely by hand?

**Comment by rozari0** [comment] 2022-12-06 21:34
> Duplicate of #106.
> 
> But how do you find that url? Do you type it entirely by hand?

Nope, most of them are DDL. If not then I extract them with yt-dlp. 
Nope, I paste it somewhere first. Then open it with Just player.

**Comment by sigma2017** [comment] 2022-12-12 18:05
Justplayer is the best because speed and simplicity. Yes, ofc you need to use a dedicated file manager or something. 
I don't think justplayer was designed for what are you asking for, my point is that this player should stay as lightweight as it is now.

**Comment by rozari0** [comment] 2022-12-12 18:08
> Justplayer is the best because speed and simplicity. Yes, ofc you need to use a dedicated file manager or something. in order to specify a streaming source... I don't think justplayer was designed for what are you asking for, my point is that this player should stay as lightweight as it is now.

Well, I don't think just a text box would slow down the app.
But if dev think it's unnecessary then I'll close issue.

**Closed** 2022-12-18 13:13 UTC
