### ISSUE TITLE
Can you remove that BIG PLAY BUTTON whenever video is paused?

### ISSUE THREAD

**Issue by sunilroyy007** [moneytoo/Player#290] opened 2022-03-10 06:50 UTC
Hey can you remove that function or gives us option to autohide or not display that ▶️ button whenever we pause the video. Sometimes we pause to check something in the video and that big button and the playback ui from downside popups and disturbs

**Comment by moneytoo** [comment] 2022-07-02 08:49
Duplicate of #195

**Closed by moneytoo** 2022-07-02 08:49 UTC
