### ISSUE TITLE
[Feature request] Change aspect ratio

### ISSUE THREAD

**Issue by kenderipa** [moneytoo/Player#523] opened 2023-10-19 08:01 UTC
Hello, 

could you perhaps add the option to change aspect ratio? I don't mean fill/stretch, but rather add some common aspects, like 4:3, 5:4, 16:9 and so on. 

Thanks!

**Comment by moneytoo** [comment] 2023-10-22 10:58
Duplicate of #321

**Closed by moneytoo** 2023-10-22 10:58 UTC
