### ISSUE TITLE
[Feature Request] Background Playback

### ISSUE THREAD

**Issue by PoetAnderson1** [moneytoo/Player#124] opened 2021-06-21 13:04 UTC
This would help to prevent a lot of battery drain.

**Comment by moneytoo** [comment] 2021-06-21 13:12
Duplicate of #44

**Closed by moneytoo** 2021-06-21 13:12 UTC

**Comment by KanadeTachibana2** [comment] 2021-09-17 21:45
can you please delete this issue?

sorry...

**Comment by KanadeTachibana2** [comment] 2021-09-18 12:51
@moneytoo I'm sorry for bothering you, but can you please delete this issue? I can't do it myself
